---

authorized_key_users: "{{ vault_authorized_key_users }}"

galaxy_user: g2main
galaxy_instance_codename: main
galaxy_instance_hostname: usegalaxy.org

docker_ssl_client_users:
  - g2main

systemd_maingalaxyservers_group_resource_controls:
  - name: supervisord
    real_memory_limit_percent: 85
    swap_limit_percent: 25
