---

controllers_group_authorized_key_users:
  - name: centos
    authorized: "{{ galaxy_admin_users }}"
  - name: g2test
    authorized: "{{ galaxy_team_users }}"
  - name: g2main
    authorized: "{{ galaxy_team_users }}"
