---

- name: Tasks for list servers
  hosts: listservers
  # If the user role in baseenv didn't precreate /var/list (for ssh private keys), we'd need to precreate it here
  tasks:

    - name: galaxyproject.postgresql role
      import_role:
        name: galaxyproject.postgresql
      tags:
        - postgres

    - name: Check for mailman3 pgdata dir
      stat:
        path: "{{ mailman3_pgdata }}"
        follow: yes
      register: __mailman3_pgdata_stat_result

    - name: Include pgdata tasks
      include_tasks: _inc_pgdata.yml
      when: not __mailman3_pgdata_stat_result.stat.exists

    - name: natefoo.postgresql_objects role
      import_role:
        name: natefoo.postgresql_objects
      become_user: postgres
      tags:
        - postgres

    - name: galaxyproject.mailman3 role
      import_role:
        name: galaxyproject.mailman3
      tags:
        - mailman

    - name: Configure list user environment
      lineinfile:
        line: "{{ item }}"
        path: /var/list/.profile
        # should already be created due to createhome
        create: yes
        owner: "{{ __mailman3_user_name }}"
        group: "{{ __mailman3_group_name }}"
        mode: "0644"
      loop:
        - export PATH="{{ mailman3_install_dir }}/bin:$PATH"
        - export MAILMAN_CONFIG_FILE='{{ mailman3_etc_dir }}/mailman.cfg'

  tags: 
    - mail
