---

- name: Include bootstrap plays
  import_playbook: bootstrap.yml
  tags:
    - never
    - bootstrap

- name: Include baseenv plays
  import_playbook: baseenv.yml

- name: Include mailserver plays
  import_playbook: mailservers.yml

- name: Include listserver plays
  import_playbook: listservers.yml

- name: Include webserver plays
  import_playbook: webservers.yml
