---

rabbitmq_users: "{{ vault_rabbitmq_users }}"

rabbitmq_ssl_certs:
  - name: server
    ca: rabbitmq
    per_host: yes
    owner: rabbitmq
    group: rabbitmq
    paths:
      - cert: /etc/rabbitmq/ssl/cert.pem
        key: /etc/rabbitmq/ssl/key.pem
        ca_cert: /etc/rabbitmq/ssl/cacert.pem

rabbitmq_config_options:
  - vm_memory_high_watermark: 0.8
  - disk_free_limit: '"500MB"'

rabbitmq_vhosts:
  - /test_pulsar
  - /main_pulsar
  - /test_internal
  - /main_internal
