---

cloud_id: jetstream_iu

# FIXME stop duplicating this between IU/TACC
slurm_cluster_name: "{{ cloud_id | replace('_', '-') }}"
slurm_controller_name: "{{ slurm_cluster_name }}0"
slurm_controller_ip: "{{ hostvars[groups.controllers[0]]['ansible_default_ipv4']['address'] }}"

galaxy_cvmfs_repos_enabled: yes

all_groups:
  - name: G-803372
    gid: 803372
  - name: TACC-ACS
    gid: 814239

all_users:
  - name: g2test
    group: G-803372
    groups: TACC-ACS
    comment: 'Galaxy Test Server'
    uid: 819456
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    group: G-803372
    groups: TACC-ACS
    comment: 'Galaxy Main Server'
    uid: 819800
    home: /home/g2main
    shell: /bin/bash

all_yum_repositories:
  - name: galaxy_gpel
    description: Galaxy Packages for Enterprise Linux $releasever - $basearch
    baseurl: https://depot.galaxyproject.org/yum/el/$releasever/$basearch/
    enabled: yes
    gpgcheck: no
