---

all_groups:
  - name: G-803372
    gid: 803372
  - name: TACC-ACS
    gid: 814239

all_users:
  - name: g2test
    group: G-803372
    groups: TACC-ACS
    comment: 'Galaxy Test Server'
    uid: 819456
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    group: G-803372
    groups: TACC-ACS
    comment: 'Galaxy Main Server'
    uid: 819800
    home: /home/g2main
    shell: /bin/bash

controller_name: jetstream-iu0
controller_ip: 10.0.0.10
