---

filesystems:
  - dev: /dev/sdb
    fstype: xfs

# FIXME: on a new install this would install over the initialized influxdb (packages install before mounts)
mounts:
  - name: /var/lib/influxdb
    src: /dev/sdb
    fstype: xfs
    owner: influxdb
    group: influxdb

nginx_conf_ssl_certificate: wildcard_cert.pem
nginx_conf_ssl_certificate_key: wildcard_privatekey.pem
nginx_conf_ssl_trusted_certificate: incommon_chain.pem

nginx_configs:
  - stats
  - sentry

nginx_default_redirect_uri: https://sentry.galaxyproject.org/

local_users:
  - name: sentry
    #group: sentry # this happens automatically if unset
    groups: nginx
    comment: 'Sentry'
    system: yes
    home: /var/opt/sentry
    createhome: yes
    shell: /bin/bash
  - name: stats
    #group: sentry # this happens automatically if unset
    groups: nginx
    comment: 'Stats'
    system: yes
    home: /var/opt/stats
    createhome: yes
    shell: /bin/bash
