---

all_links:
  - path: /galaxy
    src: /galaxy-repl
    force: yes

all_yum_repositories:
  - name: galaxy_gpel
    description: Galaxy Packages for Enterprise Linux $releasever - $basearch
    baseurl: https://depot.galaxyproject.org/yum/el/$releasever/$basearch/
    enabled: yes
    gpgcheck: no
  - name: galaxy
    state: absent
  - name: galaxy_slurm
    state: absent

all_packages:
  - git
