---

- name: Install Slurm execution host packages (apt)
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"
  when: ansible_os_family == "Debian"
  with_items:
    - slurm-wlm

- name: Install Slurm execution host packages (yum)
  yum:
    name: "{{ item }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"
  with_items:
    - munge
    - slurm
    - slurm-slurmd
  when: ansible_os_family == "RedHat"

- name: Create slurm spool directory
  file:
    path: "{{ slurmd_spool_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  notify:
    - reload slurmd
