---

cvmfsstratum1servers_group_authorized_key_users: "{{ vault_cvmfsstratum1servers_group_authorized_key_users }}"

# in MB
cvmfs_stratum1_cache_mem: 2560

cvmfsstratum1servers_group_users:
  - name: g2test
    uid: 819456
    group: G-803372
    comment: "Galaxy Test"
    home: /home/g2test
    shell: /bin/bash
  - name: g2main
    uid: 819800
    group: G-803372
    comment: "Galaxy Main"
    home: /home/g2main
    shell: /bin/bash
  - name: sandbox
    comment: "CVMFS Sandbox"
    home: /home/sandbox
    shell: /bin/bash
    system: yes

cvmfsstratum1servers_group_groups:
  - name: G-803372
    gid: 803372

cvmfs_manage_units_group: G-803372
