---

- name: Install RabbitMQ yum keys
  rpm_key:
    key: "{{ item }}"
  loop:
    - https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    - https://packagecloud.io/rabbitmq/erlang/gpgkey

- name: Install RabbitMQ repos
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: "{{ item.gpgcheck }}"
  loop:
    - name: rabbitmq_rabbitmq-server
      baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/7/$basearch
      gpgcheck: true
    - name: rabbitmq_erlang-server
      baseurl: https://packagecloud.io/rabbitmq/erlang/el/7/$basearch
      gpgcheck: true

- name: Install RabbitMQ
  yum:
    name: rabbitmq-server

# FIXME: not Ansible 2.7-compatible
#- name: Include SSL role to create/distribute SSL certs
#  include_role:
#    name: ssl
#  vars:
#    ssl_role_certs: "{{ rabbitmq_ssl_certs }}"
#  when: rabbitmq_ssl_certs is defined
#  notify:
#    - restart rabbitmq

- name: Copy RabbitMQ config
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    mode: 0444
    owner: root
    group: root
  notify:
    - restart rabbitmq

- name: Start and enable RabbitMQ
  service:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Create RabbitMQ vhosts
  rabbitmq_vhost:
    name: "{{ item }}"
    state: present
  with_items: "{{ rabbitmq_vhosts | default([]) }}"

- name: Create RabbitMQ users
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password | default(omit) }}"
    vhost: "{{ item.vhost | default(omit) }}"
    configure_priv: "{{ item.configure_priv | default(omit) }}"
    read_priv: "{{ item.read_priv | default(omit) }}"
    write_priv: "{{ item.write_priv | default(omit) }}"
    tags: "{{ item.tags | default(omit) }}"
    permissions: "{{ item.permissions | default(omit) }}"
  with_items: "{{ rabbitmq_users | default([]) }}"
