---

host_users:
  - name: sites
    comment: 'Web sites'
    system: 'yes'
    shell: '/bin/bash'
    groups: 'www-data'

directories:
  - path: /srv/nginx/status.galaxyproject.org/root
    owner: sites
    group: sites

nginx_flavor: full

nginx_conf_ssl_certificate: status.galaxyproject.org_cert.pem
nginx_conf_ssl_certificate_key: status.galaxyproject.org_privatekey.pem
nginx_conf_ssl_trusted_certificate: incommon_chain.pem
# TODO: disable 1.0, 1.1
nginx_conf_ssl_protocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2

nginx_conf_http:
  server_names_hash_bucket_size: 64

nginx_srv: /srv/nginx
nginx_configs:
  - status
