---

listservers_group_groups:
  - name: ssl-cert
    system: true
listservers_group_users:
  - name: www-data
    groups: ssl-cert

postfix_role: mda
postfix_mailname: "{{ inventory_hostname }}"

# Set this or you can't run the postfix role w/o the mailman role
postfix_mailman3_var_dir: /var/opt/mailman3/core
postfix_config:
  proxy_interfaces: "{{ ansible_ec2_public_ipv4 }}"
  transport_maps: hash:{{ postfix_mailman3_var_dir }}/data/postfix_lmtp
  local_recipient_maps: hash:{{ postfix_mailman3_var_dir }}/data/postfix_lmtp
  relay_domains: hash:{{ postfix_mailman3_var_dir }}/data/postfix_domains

listservers_group_packages:
  # not all of mailman3's cext deps have wheels available
  - build-essential
  - python3-dev

#mailman3_http_socket: :8000
#mailman3_uwsgi_static: yes

mailman3_config:
  mta:
    smtp_port: 10025

mailman3_django_superusers:
  - name: nate
    email: nate@bx.psu.edu
    pass: foo

mailman3_django_config:
  #allowed_hosts:
  #  - "{{ inventory_hostname }}"
  default_from_email: "postorius@{{ inventory_hostname }}"
  server_email: "root@{{ inventory_hostname }}"
  use_x_forwarded_host: false

# moved to all.yml for MXs
#mailman3_domains:
#  - galaxy-lists-beta.galaxyproject.org
#  - anvil-lists-beta.galaxyproject.org

mailman3_distribute_maps:
  - host: all
    mailman3_distribute_maps_dir: "/tmp"
  - host: claven.galaxyproject.org
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python3
    mailman3_postmap_command: /usr/sbin/postmap

nginx_servers:
  - mailman
nginx_ssl_servers:
  - mailman_ssl

#nginx_conf_ssl_certificate: wildcard_cert.pem
#nginx_conf_ssl_certificate_key: wildcard_privatekey.pem
nginx_ssl_role: usegalaxy-eu.certbot
nginx_conf_ssl_certificate: /etc/ssl/certs/fullchain.pem
nginx_conf_ssl_certificate_key: /etc/ssl/private/privkey-www-data.pem

certbot_auto_renew: false
certbot_environment: staging
certbot_auth_method: --webroot
certbot_domains:
  - claven.galaxyproject.org
  - galaxy-lists-beta.galaxyproject.org
  - anvil-lists-beta.galaxyproject.org
certbot_admin_email: nate@bx.psu.edu
certbot_agree_tos: --agree-tos
certbot_well_known_root: /srv/nginx/_well-known_root
certbot_share_key_users:
  - www-data
certbot_post_renewal: |
  systemctl restart nginx || true
