---

dockerswarmmanagers_group_groups: "{{ vault_dockerswarmmanagers_group_groups }}"
dockerswarmmanagers_group_users: "{{ vault_dockerswarmmanagers_group_users }}"
dockerswarmmanagers_group_authorized_key_users: "{{ vault_dockerswarmmanagers_group_authorized_key_users }}"
dockerswarmmanagers_group_private_key_users: "{{ vault_dockerswarmmanagers_group_private_key_users }}"

dockerswarmmanagers_group_crontabs:
  - name: Restart docker
    id: restart_docker
    user: root
    hour: 22
    minute: "{{ groups.dockerswarmmanagers.index(inventory_hostname) }}"
    job: systemctl restart docker.service
