---

slurm_dbd_mysql_pass: "{{ vault_slurm_dbd_mysql_pass }}"

mariadb_root_pass: "{{ vault_mariadb_root_pass }}"
mariadb_users: "{{ vault_mariadb_users }}"
mariadb_databases:
  - name: slurm_acct_db
