---

cvmfs_role: client
slurm_role: exec

galaxy_cvmfs_repos_enabled: true

galaxy_cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://cvmfs1-{{ cloud_id[10:] }}0.jetstreamlocal/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"

slurm_user:
  uid: 40302
  gid: 40302
  comment: 'Slurm Workload Manager'
  home: /var/lib/slurm
  shell: /bin/bash

slurm_cgroup_conf:
  - CgroupAutomount: yes
  - ConstrainCores: yes
  - ConstrainRAMSpace: yes
  - ConstrainSwapSpace: yes

jetstream_nfs_filesystems:
  - device: "{{ controller_name }}.jetstreamlocal:/jetstream/scratch0"
    dir: scratch0

directories:
  #- path: /galaxy-repl/test
  #- path: /galaxy-repl/main
  - path: /var/lib/slurm
    mode: "0755"

# symlinks for deps must exist due to path issues
#links:
#  - path: /galaxy
#    src: /galaxy-repl
#    force: yes
#  - path: /galaxy-repl/test/deps
#    src: /cvmfs/test.galaxyproject.org/deps
#    force: yes
#  - path: /galaxy-repl/test/tool_data
#    src: /cvmfs/data.galaxyproject.org/byhand/location
#    force: yes
#  - path: /galaxy-repl/main/deps
#    src: /cvmfs/main.galaxyproject.org/deps
#    force: yes
#  - path: /galaxy-repl/main/tool_data
#    src: /cvmfs/data.galaxyproject.org/byhand/location
#    force: yes
