---

- name: Create slurm scale directory
  file:
    path: "{{ slurm_scale_root }}"
    state: directory
    owner: "{{ slurm_scale_user }}"

- name: Install dependencies
  yum:
    name: "{{ item }}"
  with_items:
    - python-virtualenv
    - openssl-devel

- name: Create slurm scale virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ slurm_scale_root }}"
    state: latest
  with_items:
    - pip
    - setuptools
  become: yes
  become_user: "{{ slurm_scale_user }}"

# using `latest` with these can be disastrous e.g. if a new major release of Ansible is uploaded or a C extension
# dependency (e.g. cffi) is updated without wheels.
- name: Install slurm scale dependencies
  pip:
    name: "{{ item }}"
    virtualenv: "{{ slurm_scale_root }}"
  with_items:
    - ansible
    - shade
    - python-openstackclient
  become: yes
  become_user: "{{ slurm_scale_user }}"

- name: Create slurm scale ansible directory structure
  file:
    path: "{{ slurm_scale_root }}/{{ item }}"
    state: directory
    owner: "{{ slurm_scale_user }}"
  with_items:
    - sbin
    - etc/ansible
    - etc/ansible/group_vars
    - etc/ansible/group_vars/all
    - etc/ansible/inventory
    - etc/ansible/library
    - etc/ansible/templates/slurm
    - etc/ansible/roles
    - etc/ansible/roles/galaxynodeconfig
    - etc/ansible/roles/galaxynodeconfig/tasks

- name: Create slurm scale log directory
  file:
    path: "/var/log/slurm/elastic"
    state: directory
    owner: "{{ slurm_scale_user }}"

- name: Copy ansible files
  copy:
    src: "{{ item.name }}"
    dest: "{{ slurm_scale_root }}/etc/ansible/{{ item.name }}"
    owner: "{{ slurm_scale_user }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - name: ansible.cfg
    - name: resume.yml
    - name: suspend.yml
    - name: group_vars/all/spawn.yml
    - name: group_vars/all/cluster.yml
    - name: inventory/openstack.yml
    - name: library/decode
    - name: roles/galaxynodeconfig/tasks/main.yml
    - name: templates/auto.jetstream.j2

- name: Template ansible files
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ slurm_scale_root }}/etc/ansible/{{ item.name }}"
    owner: "{{ slurm_scale_user }}"
  with_items:
    - name: group_vars/all/cloud.yml

- name: Create symlinks
  file:
    path: "{{ slurm_scale_root }}/etc/ansible/{{ item.path }}"
    src: "{{ item.src }}"
    state: link
  with_items:
    - path: templates/slurm/slurm.conf.j2
      src: /etc/slurm/slurm.conf

- name: Install slurm suspend/resume script
  template:
    src: suspend_resume.sh.j2
    dest: "{{ slurm_scale_root }}/sbin/slurm_suspend"
    owner: "{{ slurm_scale_user }}"
    mode: 0755

- name: Link slurm suspend/resume script
  file:
    dest: "{{ slurm_scale_root }}/sbin/slurm_resume"
    src: "{{ slurm_scale_root }}/sbin/slurm_suspend"
    state: hard
    force: yes    # supposed to be fixed in 2.4 but it's not?

- name: Install private data
  copy:
    content: "{{ item.content }}"
    dest: "{{ slurm_scale_root }}/etc/ansible/{{ item.dest }}"
    owner: "{{ slurm_scale_user }}"
    mode: "0400"
  no_log: yes
  with_items:
    - content: "{{ slurm_ssh_key }}"
      dest: "slurm-kp.pem"
    - content: "{{ clouds_yaml | to_nice_yaml }}"
      dest: "clouds.yaml"
    - content: "{{ munge_key }}"
      dest: "munge.key"

- name: Install Ansible modules from Galaxy
  command: "{{ slurm_scale_root }}/bin/ansible-galaxy -p {{ slurm_scale_root }}/etc/ansible/roles install {{ item }}"
  args:
    creates: "{{ slurm_scale_root }}/etc/ansible/roles/{{ item }}"
  become: yes
  become_user: "{{ slurm_scale_user }}"
  with_items:
    - geerlingguy.repo-epel
    #- galaxyproject.cvmfs
    #- galaxyproject.slurm
