---

# in case we want to implement EL support
- name: Include OS vars
  include_vars:
    file: "{{ ansible_os_family | lower }}.yml"

# in case we want to implement support for another nameserver
- name: Include DNS implementation vars
  include_vars:
    file: "{{ dns_implementation | lower }}.yml"

- name: Include OS tasks
  include: "{{ ansible_os_family | lower }}.yml"

- name: Include DNS implementation tasks
  include: "{{ dns_implementation | lower }}.yml"

- name: Create DNS log directory
  file:
    state: directory
    dest: "{{ dns_log_dir }}"
    owner: "{{ dns_user }}"
    group: "{{ dns_group }}"
    mode: "0755"

- name: Install config files
  template:
    src: "{{ item.src }}.j2"
    dest: "{{ dns_config_dir }}/{{ item.dest }}"
    # this owner/mode scheme matches what debian does, even though it doesn't really make sense
    group: "{{ dns_group }}"
    mode: "0444"
    backup: yes
  with_items: "{{ dns_config_templates }}"
  notify:
    - restart dns

- name: Ensure DNS server is enabled and running
  service:
    name: "{{ dns_service_name }}"
    state: started
    enabled: yes
