---

# Prefer the TACC stratum 1
cvmfs_server_urls:
  - domain: galaxyproject.org
    urls:
      - "http://10.0.0.7/cvmfs/@fqrn@"
      - "http://cvmfs1-tacc0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-iu0.galaxyproject.org/cvmfs/@fqrn@"
      - "http://cvmfs1-psu0.galaxyproject.org/cvmfs/@fqrn@"
