---

# Telegraf is managed by dj-wasabi.telegraf

- name: Include OS vars
  include_vars: "{{ ansible_os_family | lower }}.yml"

- name: Include install tasks (RedHat)
  # TODO 2.4+: include_tasks
  include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create stats config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ stats_user }}"
    group: "{{ stats_user }}"
  with_items:
    - "{{ stats_influxdb_conf_dir }}"
    - "{{ stats_grafana_conf_dir }}"
  # if stats_user is defined, we assume non-standard dir paths
  when: stats_user is defined

- name: Create stats directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ stats_user }}"
    group: "{{ stats_user }}"  # was nginx, does it need to be?
    #mode: 0750
  with_items:
    - "{{ stats_influxdb_var_dir }}"
    - "{{ stats_grafana_data_dir }}"
    - "{{ stats_grafana_log_dir }}"
  when: stats_user is defined

- name: Include SSL role to create/distribute SSL certs
  include_role:
    name: ssl
  vars:
    ssl_role_certs: "{{ stats_ssl_certs }}"
  when: stats_ssl_certs is defined
  #notify:
  #  - restart influxdb

- name: Copy influxdb configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ stats_influxdb_conf_dir }}/{{ item }}"
    backup: true
  with_items:
    - influxdb.conf
  notify:
    - supervisorctl restart influxdb
    - service restart influxdb

- name: Copy grafana configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ stats_grafana_conf_dir }}/{{ item }}"
    group: "{{ stats_grafana_group | default(omit) }}"
    mode: 0640
    backup: true
  with_items:
    - grafana.ini
  notify:
    - supervisorctl restart grafana
    - service restart grafana

- name: Create stats slurp virtualenv
  pip:
    name: "{{ item }}"
    virtualenv: "{{ statslurp_venv_dir }}"
    state: latest
  with_items:
    - pip
    - setuptools
    - influxdb
    - psycopg2-binary
  when: stats_slurp is defined and stats_slurp

- name: Copy stats slurp scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ statslurp_venv_dir }}/bin/{{ item }}"
    mode: 0750
    owner: root
    group: stats
  with_items:
    - galaxy_slurp.py
  when: stats_slurp is defined and stats_slurp

- name: Include service tasks
  # TODO 2.4+: include_tasks
  include: service.yml
  when: not stats_use_supervisor
