---

host_authorized_key_users: "{{ vault_host_authorized_key_users }}"

host_users:
  - name: docs
    comment: 'Galaxy Docs'
  - name: wheels
    comment: 'Galaxy Wheels'
    home: /srv/nginx/wheels.galaxyproject.org
    shell: /bin/bash

mounts:
  - name: /var/lib/mailman
    src: /dev/xvdo
    fstype: xfs
    mode: 2775
    owner: root
    group: list
  - name: /srv/nginx/wheels_eggs
    src: /dev/xvdl
    fstype: xfs

ldap_server_uris:
  - ldap://localhost/ # prefer self
  - ldap://ldap2.galaxyproject.org/
  - ldap://ldap3.galaxyproject.org/

nginx_conf_ssl_certificate: wildcard_cert.pem
nginx_conf_ssl_certificate_key: wildcard_privatekey.pem
nginx_conf_ssl_trusted_certificate: incommon_chain.pem
nginx_conf_ssl_protocols:
  - TLSv1
  - TLSv1.1
  - TLSv1.2

nginx_configs:
  - wheels
  - lists
  - eggs
  - galaxydomains
  - toolshed.tools
  - galaxy.tools
  - docs

nginx_default_redirect_uri: https://galaxyproject.org/

supervisord_install: package
host_supervisor_configs:
  - pypiserver
