---

- name: Start instance(s)
  hosts: galaxynodes
  gather_facts: no
  environment:
     OS_CLOUD: "{{ cloud_id }}"
     OS_IDENTITY_API_VERSION: '3'
  tasks:
    - name: Start instance
      os_server_action:
        cloud: "{{ cloud_id }}"
        server: "{{ inventory_hostname }}"
        action: "start"
      delegate_to: localhost
      register: started_out

    - name: Wait for instance to become accessible
      wait_for_connection:

    - name: Copy slurm.conf
      copy:
        src: /etc/slurm/slurm.conf
        dest: /etc/slurm/slurm.conf
      become: yes
      register: slurm_conf

    - name: Restart slurmd
      service:
        name: slurmd
        state: restarted
      become: yes
      when: slurm_conf is changed

    - name: Log IP address
      debug:
        var: ansible_host

    - name: Update slurm controller with instance IP
      command: scontrol update nodename={{ inventory_hostname }} nodeaddr={{ ansible_host }}
      delegate_to: localhost
