---

grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_pass: "{{ vault_grafana_admin_pass }}"
grafana_secret_key: "{{ vault_grafana_secret_key }}"

galaxy_test_grafana_db_password: "{{ vault_galaxy_test_grafana_db_password }}"
galaxy_main_grafana_db_password: "{{ vault_galaxy_main_grafana_db_password }}"

statsservers_group_packages:
  - '@development'
  - python-virtualenv
  - python-psycopg2
  # sentry deps
  - memcached
  - postgresql95-devel
  - libxml2-devel
  - libxslt-devel
  - libffi-devel
  - openssl-devel

postgresql_version: '9.5'

postgresql_objects_users:
  - name: sentry
  - name: graphite

postgresql_objects_databases:
  - name: sentry
    owner: sentry
  - name: graphite
    owner: graphite

supervisord_install: package

supervisord_group_configs:
  - sentry
  - stats

sentry_conf_email_host: 'localhost'
stats_conf_email_host: 'localhost:25'
stats_conf_email_from: 'stats@stats.galaxyproject.org'

# used in the nginx template, which is run in a play that does not include the
# sentry role
sentry_sock_dir: /var/opt/sentry/run

group_crontabs:
  - id: slurp_galaxy_stats_test
    name: Slurp Galaxy Test Stats
    user: stats
    minute: "*/5"
    job: "/srv/statslurp/bin/galaxy_slurp.py test"
  - id: slurp_galaxy_stats_main
    name: Slurp Galaxy Main Stats
    user: stats
    minute: "*/5"
    job: "/srv/statslurp/bin/galaxy_slurp.py main"
