---

grafana_admin_user: "{{ vault_grafana_admin_user }}"
grafana_admin_pass: "{{ vault_grafana_admin_pass }}"
grafana_secret_key: "{{ vault_grafana_secret_key }}"

galaxy_test_grafana_db_password: "{{ vault_galaxy_test_grafana_db_password }}"
galaxy_main_grafana_db_password: "{{ vault_galaxy_main_grafana_db_password }}"

statsservers_group_packages:
  - '@development'
  - python-virtualenv
  - python-psycopg2
  # sentry deps
  - memcached
  - postgresql95-devel
  - libxml2-devel
  - libxslt-devel
  - libffi-devel
  - openssl-devel

postgresql_version: '9.5'

postgresql_objects_users:
  - name: sentry
  - name: graphite

postgresql_objects_databases:
  - name: sentry
    owner: sentry
  - name: graphite
    owner: graphite

supervisord_install: package

supervisord_group_configs:
  - sentry
  - stats

sentry_conf_email_host: 'localhost'
stats_conf_email_host: 'localhost:25'
stats_conf_email_from: 'stats@stats.galaxyproject.org'

# used in the nginx template, which is run in a play that does not include the
# sentry role
sentry_sock_dir: /var/opt/sentry/run

group_crontabs:
  - id: slurp_galaxy_stats_test
    name: Slurp Galaxy Test Stats
    user: stats
    minute: "*/5"
    job: "/srv/statslurp/bin/galaxy_slurp.py test"
  - id: slurp_galaxy_stats_main
    name: Slurp Galaxy Main Stats
    user: stats
    minute: "*/5"
    job: "/srv/statslurp/bin/galaxy_slurp.py main"

# separate db filtering for statsd (Galaxy timing) and system stuff using
#   https://github.com/influxdata/telegraf/issues/1778
telegraf_agent_output:
  - type: influxdb
    config:
      - urls = ["http://localhost:8086"]
      - database = "system"
      - '[outputs.influxdb.tagdrop]'
      - '  influxdb_database = ["*"]'
  - type: influxdb
    config:
      - urls = ["http://localhost:8086"]
      - database = "telegraf"
      - 'tagexclude = ["influxdb_database"]'
      - '[outputs.influxdb.tagpass]'
      - '  influxdb_database = ["telegraf"]'

telegraf_plugins_default:
  - plugin: statsd
    config:
      - service_address = "0.0.0.0:8125"
      - delete_gauges = false
      - delete_counters = false
      - delete_sets = false
      - delete_timings = true
      - percentiles = [90]
      - metric_separator = "_"
      - parse_data_dog_tags = false
      - allowed_pending_messages = 10000
      - percentile_limit = 1000
      - udp_packet_size = 1500
      - '[inputs.statsd.tags]'
      - '  influxdb_database = "telegraf"'
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
