---

- name: Launch instance(s)
  hosts: instances
  gather_facts: no
  environment:
    OS_CLOUD: "{{ openstack_cloud_id }}"
    OS_IDENTITY_API_VERSION: '3'
  roles:
    - openstack

# NOTE: you *must* run the openstack role for the paths role, which needs the volume device

- name: Tasks for "base environment" hosts
  hosts: baseenv
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    - role: requiretty        # Disable requiretty for Ansible ssh pipelining
      tags: initial,requiretty
    - role: geerlingguy.repo-epel
      tags: packages
    - role: packages          # Install packages
      tags: system,packages
    - role: users             # Create users and set up authentication keys
      tags: system,users
    - role: paths             # Configure path permissions, filesystems
      tags: system,paths
    - role: copy              # Copy arbitrary files/templates
      tags: system,copy
    - role: cron              # Create cron jobs
      tags: system,cron
    - role: services          # Manage services
      tags: system,services
  tags: initial

- name: CVMFS tasks
  hosts: cvmfsclients
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    #- role: packages
    #  tags: packages
    - role: galaxyproject.cvmfs
  tags: cvmfs

- name: NFS tasks
  hosts: controllers:galaxynodes
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    - role: jetstream_nfs
  tags: nfs

#- name: Update /etc/hosts
#  hosts: controllers:galaxynodes
#  remote_user: centos
#  become: yes
#  become_method: sudo
#  tasks:
#    - name: Update /etc/hosts
#      template:
#        src: templates/etc/hosts.j2
#        dest: /etc/hosts

- name: Install supervisor
  hosts: all
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    - role: supervisor
      when: supervisord_group_configs is defined or supervisord_host_configs is defined
      tags: supervisor,services

# This has to be last for slurm elastic (everything must be configured/done when slurmd starts)
- name: Tasks for slurm hosts
  hosts: slurmservers:slurmclients
  remote_user: centos
  become: yes
  become_method: sudo
  roles:
    - galaxyproject.slurm
    - slurmscale
  tags: slurm
