---

ldap_server_uris:
  - ldap://localhost/ # prefer self
  - ldap://ldap2.galaxyproject.org/
  - ldap://ldap1.galaxyproject.org/

nginx_conf_ssl_certificate: wildcard_cert.pem
nginx_conf_ssl_certificate_key: wildcard_privatekey.pem
nginx_conf_ssl_trusted_certificate: incommon_chain.pem

nginx_flavor: full

nginx_configs:
  - duvel
  - jenkins
  - images-proxy

nginx_default_redirect_uri: https://galaxyproject.org/

nginx_conf_http:
  server_names_hash_bucket_size: 128
  proxy_read_timeout: 300

# TODO: implement me
nginx_pam_config_dest: /etc/pam.d/nginx
