---

host_packages:
  - rsync   # need >=3.1.0 for --info

local_users:
  - name: zfsdump-orval
    group: zfsdump-orval
    comment: 'ZFS receive orval'
    home: /home/zfsdump-orval
    shell: /bin/bash
  - name: zfsdump-radegast
    group: zfsdump-radegast
    comment: 'ZFS receive radegast'
    home: /home/zfsdump-radegast
    shell: /bin/bash
  - name: zfsdump-leeroy
    group: zfsdump-leeroy
    comment: 'ZFS receive leeroy'
    home: /home/zfsdump-leeroy
    shell: /bin/bash
  - name: zfsdump-biostar
    group: zfsdump-biostar
    home: /home/zfsdump-biostar
    shell: /bin/bash
  - name: nate
    uid: 2048
    group: nate
    gid: 2048
    comment: Nate Coraor
    home: /home/nate
    shell: /bin/bash

zfs_filesystems:
  - name: zones/westvleteren/backup
    atime: "off"
    exec: "off"
    setuid: "off"
    compression: lz4
  - name: zones/westvleteren/backup/orval
    owner: zfsdump-orval
    group: zfsdump-orval
  - name: zones/westvleteren/backup/radegast
    owner: zfsdump-radegast
    group: zfsdump-radegast
  - name: zones/westvleteren/backup/radegast/postgres
    owner: zfsdump-radegast
    group: zfsdump-radegast
  - name: zones/westvleteren/backup/radegast/postgres/current
    owner: zfsdump-radegast
    group: zfsdump-radegast
  - name: zones/westvleteren/backup/radegast/testshed
    owner: zfsdump-radegast
    group: zfsdump-radegast
  - name: zones/westvleteren/backup/radegast/mainshed
    owner: zfsdump-radegast
    group: zfsdump-radegast
  - name: zones/westvleteren/backup/leeroy
    owner: zfsdump-leeroy
    group: zfsdump-leeroy
  - name: zones/westvleteren/backup/leeroy/jenkins
    owner: zfsdump-leeroy
    group: zfsdump-leeroy
  - name: zones/westvleteren/backup/biostar
    owner: zfsdump-biostar
    group: zfsdump-biostar
  - name: zones/westvleteren/backup/biostar/data
    owner: zfsdump-biostar
    group: zfsdump-biostar

zfs_permissions:
  - name: zones/westvleteren/backup/orval
    users: zfsdump-orval
    permissions: compression,create,mount,receive
  - name: zones/westvleteren/backup/radegast
    users: zfsdump-radegast
    permissions: snapshot
  - name: zones/westvleteren/backup/leeroy
    users: zfsdump-leeroy
    permissions: snapshot
  - name: zones/westvleteren/backup/biostar
    users: zfsdump-biostar
    permissions: snapshot

directories:
  - path: /zones/westvleteren/backup/radegast/postgres/active
    owner: zfsdump-radegast
    group: zfsdump-radegast

crontabs:
  - id: biostar_backup
    name: Biostar Backup
    user: zfsdump-biostar
    minute: 40
    job: rsync -a --delete www@biostar.usegalaxy.org:/home/www/data/ /zones/westvleteren/backup/biostar/data && /usr/sbin/zfs snapshot zones/westvleteren/backup/biostar/data@`date -u +\%Y\%m\%dT\%H\%M\%SZ`
