---

# Include once to write/set, include a second time to remove/clear

- name: Handle clouds.yaml
  hosts: instances
  connection: local
  become: false
  tasks:
    - name: Write clouds.yaml and ssh key file
      copy:
        content: "{{ item.content }}"
        dest: "{{ item.dest }}"
        mode: "0400"
      with_items:
        - { dest: "{{ inventory_dir }}/clouds.yaml", content: "{{ clouds_yaml | to_nice_yaml }}" }
        - { dest: "{{ ansible_ssh_private_key_file }}", content: "{{ swarm_ssh_key }}" }
      delegate_to: localhost
      run_once: yes
      no_log: yes
    - name: Write ssh_config.jetstream
      template:
        src: "ssh_config.jetstream.j2"
        dest: "{{ inventory_dir }}/ssh_config.{{ cloud_id }}"
      delegate_to: localhost
    - name: Set cleanup list
      set_fact:
        clean_on_failure:
          - "{{ inventory_dir }}/clouds.yaml"
          - "{{ ansible_ssh_private_key_file }}"
          - "{{ inventory_dir }}/ssh_config.{{ cloud_id }}"
    - name: Set cloud fact
      set_fact:
        clouds: "{{ clouds_yaml.clouds }}"
      delegate_to: localhost
