---

- name: Set up for spawn
  hosts: baseinstances
  connection: local
  tasks:
    - name: Create instances group
      group_by:
        key: instances

- name: Include clouds.yaml play
  include: _inc_clouds_yaml.yml

- name: Include spawn play
  include: _inc_spawn.yml

- name: Configure instance(s)
  hosts: baseinstances
  connection: ssh
  become: yes
  environment:
    HISTFILE: null
  pre_tasks:
    - block:
        - name: Make filesystem for /var/lib/docker
          filesystem:
            dev: "{{ volume_dev }}"
            fstype: xfs
        - name: Mount /var/lib/docker
          mount:
            src: "{{ volume_dev }}"
            name: "/var/lib/docker"
            fstype: xfs
            state: mounted
      rescue:
        - include: _inc_clean.yml
  roles:
    - docker
  post_tasks:
    - block:
        - name: Install qemu-guest-agent
          yum:
            name: qemu-guest-agent
        - name: Start qemu-guest-agent
          service:
            name: qemu-guest-agent
            state: started
        - name: Stop services for cleaning
          service:
            name: "{{ item }}"
            state: stopped
          with_items:
            - tuned
            - rsyslog
            - docker
        - name: Stop auditd
          command: service auditd stop
        - name: Clean yum
          command: yum clean all
        - name: Remove logs
          file:
            path: "/var/log/{{ item }}"
            state: absent
          with_items:
            - audit/audit.log
            - tuned/tuned.log
            - dmesg
            - boot.log
            - maillog
            - btmp
            - cloud-init-output.log
            - cloud-init.log
            - wtmp
            - lastlog
            - secure
            - cron
            - messages
            - yum.log
        - name: Remove home directory files
          file:
            path: "~{{ ansible_user }}/{{ item }}"
            state: absent
          with_items:
            - .ssh
            - .bash_history
        - name: Remove other files
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            - /root/.bash_history
            - /etc/hostname
        - name: Unmount /var/lib/docker
          mount:
            name: "/var/lib/docker"
            state: unmounted
        - name: Touch /.autorelabel
          file:
            path: /.autorelabel
            state: touch
      rescue:
        - include: _inc_clean.yml

# always cleans secrets
- name: Include delete play
  include: _inc_delete.yml
