---

# 500 GB why not
cvmfs_quota_limit: 512000

galaxynodes_group_authorized_key_users:
  - name: g2test
    authorized: "{{ galaxy_team_users }}"
  - name: g2main
    authorized: "{{ galaxy_team_users }}"

galaxynodes_group_packages:
  - collectl
  - lzo
  - libcgroup-tools
