---

# 500 GB why not
cvmfs_quota_limit: 512000

galaxynodes_group_authorized_key_users:
  - name: g2test
    authorized: "{{ galaxy_team_users }}"
  - name: g2main
    authorized: "{{ galaxy_team_users }}"

galaxynodes_group_packages:
  - collectl
  - lzo
  - libcgroup-tools
  - singularity-runtime
  # packages for older tools
  - perl-Data-Dumper

galaxynodes_group_files:
  - src: system/cleancgroups.py
    dest: ~root/cleancgroups.py

galaxynodes_group_crontabs:
  - id: clean_cgroups
    name: Clean old cgroups
    user: root
    minute: "*/5"
    job: "python /root/cleancgroups.py >> /var/log/cleancgroups.log 2>&1"
