---

galaxy_user: g2test
galaxy_instance_codename: test
galaxy_instance_hostname: test.galaxyproject.org

testgalaxyservers_group_authorized_key_users:
  - name: g2test
    authorized: "{{ galaxy_team_users }}"
  - name: gxsrc
    authorized: "{{ galaxy_team_users }}"

systemd_testgalaxyservers_group_resource_controls:
  - name: supervisord
    real_memory_limit_percent: 70
    swap_limit_percent: 25
