---

- name: supervisorctl restart influxdb
  supervisorctl:
    name: stats:influxd
    state: restarted
  when: stats_use_supervisor

- name: service restart influxdb
  service:
    name: "{{ influxdb_service_name }}"
    state: restarted
  when: not stats_use_supervisor

- name: supervisorctl restart grafana
  supervisorctl:
    name: stats:grafana-server
    state: restarted
  when: stats_use_supervisor

- name: service restart grafana
  service:
    name: "{{ grafana_service_name }}"
    state: restarted
  when: not stats_use_supervisor
